gem "sinatra"
gem "sqlite3"
gem "sequel"
gem "rspec"
gem "ZenTest"
gem "autotest"
gem "autotest-fsevent"
gem "autotest-growl"
gem "rack"
gem "rack-test"


group :development do
	gem "shotgun"
	gem "tux"
end
